# Site settings
title: 你好511
email: 511511@super.vip.qq.com
description: "这仅仅是开了一个玩笑，并不针对个人"
baseurl: ""
url: "http://dou－b.com"
＃twitter_username: jekyllrb
＃github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
