# Site settings
title: 方非胖，你好
email: xufangfei@super.vip.qq.com
description: "这仅仅是开了一个玩笑，并不针对个人"
baseurl: ""
url: "http://dou－b.com"
＃twitter_username: jekyllrb
＃github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
